version: "3.9"

services:
  backend:
    build:
      context: ./backend/telegram-scrapper
    container_name: telegram-backend
    env_file:
      - ./backend/telegram-scrapper/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/telegram-scrapper/downloaded_media:/app/downloaded_media
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongo-data:
